#!/bin/bash
# setup — Project setup automation tool
# Generate and execute setup scripts for projects created with prj/agt

SETUP_VERSION="0.1.0"
SETUP_DIR="${SETUP_DIR:-$HOME/.setup}"
SETUP_CONFIG="$SETUP_DIR/config.json"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Ensure setup directory exists
mkdir -p "$SETUP_DIR"

# Initialize config if it doesn't exist
if [ ! -f "$SETUP_CONFIG" ]; then
    echo '{}' > "$SETUP_CONFIG"
fi

help() {
    cat << HELP
setup v$SETUP_VERSION — Project setup automation

Generate and execute setup scripts for projects created with prj/agt

USAGE:
    setup <command> [options]

COMMANDS:
    init                Initialize setup in current directory
    generate            Generate setup script from project structure
    run                 Execute setup script
    status              Show setup status
    clean               Remove generated setup files

OPTIONS:
    -h, --help          Show this help message
    -v, --version       Show version

EXAMPLES:
    setup init                  Initialize setup in current project
    setup generate              Generate setup.sh from project structure
    setup run                    Execute setup.sh
    setup status                 Show what has been set up

HELP
}

version() {
    echo "setup v$SETUP_VERSION"
}

# Initialize setup in current directory
init_setup() {
    if [ ! -f "setup.json" ]; then
        cat > setup.json << 'INIT'
{
    "name": "",
    "type": "",
    "dependencies": [],
    "commands": {
        "pre_install": [],
        "install": [],
        "post_install": [],
        "configure": []
    },
    "environment": {
        "variables": {},
        "files": []
    }
}
INIT
        echo "${GREEN}✓${NC} Initialized setup.json"
        echo "${YELLOW}Edit setup.json to configure your project setup${NC}"
    else
        echo "${YELLOW}setup.json already exists${NC}"
    fi
}

# Generate setup script from project structure
generate_setup() {
    local project_type=""
    local setup_file="setup-generated.sh"

    # Detect project type
    if [ -f "pyproject.toml" ] || [ -f "requirements.txt" ]; then
        project_type="python"
    elif [ -f "package.json" ]; then
        project_type="node"
    elif [ -f "go.mod" ]; then
        project_type="go"
    elif [ -f "Cargo.toml" ]; then
        project_type="rust"
    else
        project_type="generic"
    fi

    echo "${BLUE}Detected project type: $project_type${NC}"

    # Generate setup script
    cat > "$setup_file" << GENERATE
#!/bin/bash
# Auto-generated setup script for $(basename "$PWD")
# Generated by setup v$SETUP_VERSION

set -e

echo "🚀 Setting up $(basename "$PWD")..."

GENERATE

    # Add project-specific setup commands
    case "$project_type" in
        python)
            cat >> "$setup_file" << PYTHON
# Python project setup

# Check if Python is installed
if ! command -v python3 &> /dev/null; then
    echo "❌ Python 3 is required but not installed"
    exit 1
fi

# Create virtual environment if it doesn't exist
if [ ! -d "venv" ]; then
    echo "📦 Creating virtual environment..."
    python3 -m venv venv
fi

# Activate virtual environment
echo "🔧 Activating virtual environment..."
source venv/bin/activate

# Install dependencies
if [ -f "requirements.txt" ]; then
    echo "📥 Installing dependencies from requirements.txt..."
    pip install -r requirements.txt
fi

if [ -f "pyproject.toml" ]; then
    echo "📥 Installing package in editable mode..."
    pip install -e .
fi

echo "${GREEN}✓${NC} Python project setup complete"
echo "Run: source venv/bin/activate"
PYTHON
            ;;
        node)
            cat >> "$setup_file" << NODE
# Node.js project setup

# Check if Node.js is installed
if ! command -v node &> /dev/null; then
    echo "❌ Node.js is required but not installed"
    exit 1
fi

# Check if npm is installed
if ! command -v npm &> /dev/null; then
    echo "❌ npm is required but not installed"
    exit 1
fi

# Install dependencies
if [ -f "package.json" ]; then
    echo "📥 Installing dependencies..."
    npm install
fi

echo "${GREEN}✓${NC} Node.js project setup complete"
NODE
            ;;
        go)
            cat >> "$setup_file" << GO
# Go project setup

# Check if Go is installed
if ! command -v go &> /dev/null; then
    echo "❌ Go is required but not installed"
    exit 1
fi

# Download dependencies
if [ -f "go.mod" ]; then
    echo "📥 Downloading Go modules..."
    go mod download
    go mod tidy
fi

echo "${GREEN}✓${NC} Go project setup complete"
GO
            ;;
        rust)
            cat >> "$setup_file" << RUST
# Rust project setup

# Check if Rust is installed
if ! command -v cargo &> /dev/null; then
    echo "❌ Rust is required but not installed"
    echo "   Install from: https://rustup.rs/"
    exit 1
fi

# Build project
echo "🔨 Building project..."
cargo build

echo "${GREEN}✓${NC} Rust project setup complete"
RUST
            ;;
        generic)
            cat >> "$setup_file" << GENERIC
# Generic project setup

echo "📝 No specific setup detected for this project type"
echo "Edit $setup_file to add custom setup commands"
GENERIC
            ;;
    esac

    # Make the script executable
    chmod +x "$setup_file"

    echo "${GREEN}✓${NC} Generated $setup_file"
    echo "${YELLOW}Run: ./$setup_file${NC}"
}

# Execute setup script
run_setup() {
    local setup_file="setup-generated.sh"

    if [ ! -f "$setup_file" ]; then
        echo "${RED}❌ No setup script found${NC}"
        echo "Run: setup generate"
        exit 1
    fi

    echo "${BLUE}Running setup script...${NC}"
    ./"$setup_file"
}

# Show setup status
show_status() {
    local setup_file="setup-generated.sh"
    local config_file="setup.json"

    echo "Setup Status for: $(basename "$PWD")"
    echo ""

    if [ -f "$config_file" ]; then
        echo "${GREEN}✓${NC} setup.json exists"
    else
        echo "${YELLOW}○${NC} setup.json not found (run: setup init)"
    fi

    if [ -f "$setup_file" ]; then
        echo "${GREEN}✓${NC} $setup_file exists"
    else
        echo "${YELLOW}○${NC} $setup_file not found (run: setup generate)"
    fi

    echo ""

    # Detect project type
    if [ -f "pyproject.toml" ] || [ -f "requirements.txt" ]; then
        echo "Project Type: Python"
        [ -d "venv" ] && echo "${GREEN}✓${NC} Virtual environment created" || echo "${YELLOW}○${NC} No virtual environment"
    elif [ -f "package.json" ]; then
        echo "Project Type: Node.js"
        [ -d "node_modules" ] && echo "${GREEN}✓${NC} Dependencies installed" || echo "${YELLOW}○${NC} Dependencies not installed"
    elif [ -f "go.mod" ]; then
        echo "Project Type: Go"
    elif [ -f "Cargo.toml" ]; then
        echo "Project Type: Rust"
    else
        echo "Project Type: Unknown"
    fi
}

# Clean generated files
clean_setup() {
    local setup_file="setup-generated.sh"

    if [ -f "$setup_file" ]; then
        rm "$setup_file"
        echo "${GREEN}✓${NC} Removed $setup_file"
    else
        echo "${YELLOW}No setup file to remove${NC}"
    fi
}

# Main command handler
case "$1" in
    init)
        init_setup
        ;;
    generate)
        generate_setup
        ;;
    run)
        run_setup
        ;;
    status)
        show_status
        ;;
    clean)
        clean_setup
        ;;
    -h|--help|"")
        help
        ;;
    -v|--version)
        version
        ;;
    *)
        echo "${RED}Unknown command: $1${NC}"
        echo ""
        help
        exit 1
        ;;
esac
