#!/usr/bin/env python3
"""
crw - CrewAI Workflow Manager
Create, manage, and orchestrate AI agent crews with YAML configuration
"""

import os
import sys
import json
import argparse
import subprocess
from pathlib import Path
from datetime import datetime
import yaml

# Constants
CREW_DIR = Path.home() / ".crew"
CREWS_FILE = CREW_DIR / "crews.json"
CREW_YAML_TEMPLATE = """# CrewAI Workflow Configuration
# Define your agents and tasks here

version: "1.0"

name: {crew_name}
description: {crew_description}

# Agent definitions
agents:
  - id: agent1
    name: "Agent 1"
    role: "Research Agent"
    goal: "Find and analyze information"
    backstory: "An expert researcher with attention to detail"
    llm: "openai/gpt-4"
    tools: []
    verbose: true

  - id: agent2
    name: "Agent 2"
    role: "Writer Agent"
    goal: "Create clear and engaging content"
    backstory: "A skilled writer with years of experience"
    llm: "openai/gpt-4"
    tools: []
    verbose: true

# Task definitions
tasks:
  - id: task1
    name: "Research Task"
    description: "Research the topic thoroughly"
    expected_output: "A comprehensive report"
    agent: agent1
    context: []

  - id: task2
    name: "Writing Task"
    description: "Write content based on research"
    expected_output: "Well-written article"
    agent: agent2
    depends_on: [task1]

# Execution settings
execution:
  process: "sequential"  # sequential or hierarchical
  manager_llm: "openai/gpt-4"
  verbose: true
"""

EXECUTION_SCRIPT_TEMPLATE = """#!/bin/bash
# Crew Execution Script
# Generated by crw on {timestamp}

set -e

CREW_NAME="{crew_name}"
CREW_DIR="$HOME/.crew/$CREW_NAME"

echo "🚀 Starting crew: $CREW_NAME"
echo "📂 Crew directory: $CREW_DIR"
echo ""

# Check if crew exists
if [ ! -d "$CREW_DIR" ]; then
    echo "❌ Crew not found: $CREW_NAME"
    exit 1
fi

cd "$CREW_DIR"

# Run the crew (placeholder - integrate with CrewAI or custom agent system)
echo "📋 Executing crew workflow..."
echo ""
echo "Agents:"
cat crew.yaml | grep -A 2 "  - id:" | grep -E "(id:|name:|role:)" | head -15
echo ""
echo "Tasks:"
cat crew.yaml | grep -A 3 "  - id:" | grep -E "(id:|name:|description:)" | head -15
echo ""

# You would integrate this with actual CrewAI or your agent system here
# For now, this is a demonstration of the workflow structure

echo "✅ Crew execution complete!"
"""

def init():
    """Initialize the crew directory structure"""
    CREW_DIR.mkdir(parents=True, exist_ok=True)
    if not CREWS_FILE.exists():
        CREWS_FILE.write_text(json.dumps({}, indent=2))
    print(f"✅ Initialized crew directory: {CREW_DIR}")

def list_crews():
    """List all available crews"""
    if not CREWS_FILE.exists():
        init()

    crews = json.loads(CREWS_FILE.read_text())

    if not crews:
        print("📭 No crews found. Create one with: crw create <name>")
        return

    print(f"📋 Available crews ({len(crews)}):")
    print()
    for crew_id, crew_info in crews.items():
        print(f"  • {crew_id}")
        print(f"    {crew_info.get('description', 'No description')}")
        print(f"    Created: {crew_info.get('created', 'Unknown')}")
        print()

def create_crew(name, description=""):
    """Create a new crew"""
    if not CREWS_FILE.exists():
        init()

    crews = json.loads(CREWS_FILE.read_text())

    if name in crews:
        print(f"❌ Crew '{name}' already exists")
        sys.exit(1)

    # Create crew directory
    crew_dir = CREW_DIR / name
    crew_dir.mkdir(parents=True, exist_ok=True)

    # Create crew.yaml
    crew_yaml = CREW_YAML_TEMPLATE.format(
        crew_name=name,
        crew_description=description or f"Auto-generated crew: {name}"
    )
    (crew_dir / "crew.yaml").write_text(crew_yaml)

    # Create execution script
    exec_script = EXECUTION_SCRIPT_TEMPLATE.format(
        crew_name=name,
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    )
    exec_file = crew_dir / "run.sh"
    exec_file.write_text(exec_script)
    exec_file.chmod(0o755)

    # Create output directory
    (crew_dir / "output").mkdir(exist_ok=True)

    # Register crew
    crews[name] = {
        "description": description or f"Auto-generated crew: {name}",
        "created": datetime.now().isoformat(),
        "path": str(crew_dir)
    }
    CREWS_FILE.write_text(json.dumps(crews, indent=2))

    print(f"✅ Created crew: {name}")
    print(f"📂 Location: {crew_dir}")
    print(f"📝 Config: {crew_dir / 'crew.yaml'}")
    print(f"🚀 Run: ./run.sh")

def show_crew(name):
    """Show crew details"""
    if not CREWS_FILE.exists():
        init()

    crews = json.loads(CREWS_FILE.read_text())

    if name not in crews:
        print(f"❌ Crew '{name}' not found")
        sys.exit(1)

    crew_info = crews[name]
    crew_dir = Path(crew_info["path"])

    print(f"📋 Crew: {name}")
    print(f"📝 {crew_info['description']}")
    print(f"📅 Created: {crew_info['created']}")
    print(f"📂 Location: {crew_dir}")
    print()

    # Show crew.yaml contents
    crew_yaml = (crew_dir / "crew.yaml")
    if crew_yaml.exists():
        print("📄 Configuration (crew.yaml):")
        print("-" * 60)
        try:
            config = yaml.safe_load(crew_yaml.read_text())
            print(f"Version: {config.get('version', 'N/A')}")
            print(f"Agents: {len(config.get('agents', []))}")
            print(f"Tasks: {len(config.get('tasks', []))}")
            print()
            print("Agents:")
            for agent in config.get('agents', []):
                print(f"  • {agent.get('name')} ({agent.get('role')})")
            print()
            print("Tasks:")
            for task in config.get('tasks', []):
                deps = task.get('depends_on', [])
                deps_str = f" (depends on: {', '.join(deps)})" if deps else ""
                print(f"  • {task.get('name')}{deps_str}")
        except Exception as e:
            print(f"⚠️  Error parsing YAML: {e}")
            print(crew_yaml.read_text()[:500])

def run_crew(name):
    """Run a crew"""
    if not CREWS_FILE.exists():
        init()

    crews = json.loads(CREWS_FILE.read_text())

    if name not in crews:
        print(f"❌ Crew '{name}' not found")
        sys.exit(1)

    crew_dir = Path(crews[name]["path"])
    exec_script = crew_dir / "run.sh"

    if not exec_script.exists():
        print(f"❌ Execution script not found: {exec_script}")
        sys.exit(1)

    print(f"🚀 Running crew: {name}")
    print()

    # Execute the run script
    subprocess.run([str(exec_script)], check=True)

def delete_crew(name):
    """Delete a crew"""
    if not CREWS_FILE.exists():
        init()

    crews = json.loads(CREWS_FILE.read_text())

    if name not in crews:
        print(f"❌ Crew '{name}' not found")
        sys.exit(1)

    # Remove crew directory
    crew_dir = Path(crews[name]["path"])
    if crew_dir.exists():
        subprocess.run(["rm", "-rf", str(crew_dir)])

    # Remove from registry
    del crews[name]
    CREWS_FILE.write_text(json.dumps(crews, indent=2))

    print(f"🗑️  Deleted crew: {name}")

def main():
    parser = argparse.ArgumentParser(
        description="crw - CrewAI Workflow Manager",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  crw init              Initialize crew directory
  crw create my-crew    Create a new crew
  crw list              List all crews
  crw show my-crew      Show crew details
  crw run my-crew       Run a crew
  crw delete my-crew    Delete a crew
        """
    )

    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # init command
    subparsers.add_parser("init", help="Initialize crew directory")

    # create command
    create_parser = subparsers.add_parser("create", help="Create a new crew")
    create_parser.add_argument("name", help="Crew name")
    create_parser.add_argument("-d", "--description", help="Crew description")

    # list command
    subparsers.add_parser("list", help="List all crews")

    # show command
    show_parser = subparsers.add_parser("show", help="Show crew details")
    show_parser.add_argument("name", help="Crew name")

    # run command
    run_parser = subparsers.add_parser("run", help="Run a crew")
    run_parser.add_argument("name", help="Crew name")

    # delete command
    delete_parser = subparsers.add_parser("delete", help="Delete a crew")
    delete_parser.add_argument("name", help="Crew name")

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        sys.exit(1)

    # Execute command
    if args.command == "init":
        init()
    elif args.command == "create":
        create_crew(args.name, args.description)
    elif args.command == "list":
        list_crews()
    elif args.command == "show":
        show_crew(args.name)
    elif args.command == "run":
        run_crew(args.name)
    elif args.command == "delete":
        delete_crew(args.name)

if __name__ == "__main__":
    main()
